In [22]:
# Task 1: Calculate the mean and standard deviation of a NumPy array

import numpy as np
arr= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean_1 = np.mean(arr)
std_1 = np.std(arr)
print("mean of the array:",mean_1,"\nstandard deviation of the array:",std_1)

mean of the array: 5.5 
standard deviation of the array: 2.8722813232690143


In [20]:
# Task 2: Generate a random matrix of size 5x5 and find the min and max values along each row and column

matrix = np.random.rand(5, 5)             # for creating a random matrix of size 5x5 random.rand function is used

min_values_rows = np.min(matrix, axis=1)    # axis=1 indicates along the row wise
max_values_rows = np.max(matrix, axis=1)

min_values_columns = np.min(matrix, axis=0)   # axis=0 indicates along the column wise
max_values_columns = np.max(matrix, axis=0)

print(matrix,"\n\nminimum value along rows:",min_values_rows,"\n\nmaximum value along rows",max_values_rows)
print("\nminimum value along columns",min_values_columns,"\n\nmaximum value along columns",max_values_columns)

[[0.36572801 0.94530298 0.66911311 0.00724821 0.60261187]
 [0.99473986 0.61712414 0.12925544 0.31649869 0.61165631]
 [0.5681828  0.8048407  0.14219726 0.47927824 0.79853914]
 [0.35485251 0.8749371  0.46663393 0.59962024 0.23951556]
 [0.0845603  0.22050254 0.1498997  0.44983864 0.85873391]] 

minimum value along rows: [0.00724821 0.12925544 0.14219726 0.23951556 0.0845603 ] 

maximum value along rows [0.94530298 0.99473986 0.8048407  0.8749371  0.85873391]

minimum value along columns [0.0845603  0.22050254 0.12925544 0.00724821 0.23951556] 

maximum value along columns [0.99473986 0.94530298 0.66911311 0.59962024 0.85873391]


In [24]:
# Task 3: Implement the function to calculate the cosine similarity between two vectors

def cos_sim(vec1, vec2):
    
    dot_product = np.dot(vec1, vec2)     #gives the dot product of vector1 and vector2
    
    norm_vec1 = np.linalg.norm(vec1)     #here in order to get magnitude of vector we use linalg.norm function
    norm_vec2 = np.linalg.norm(vec2)
    
    return dot_product / (norm_vec1 * norm_vec2)

# Example vectors for cosine similarity
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])

print("cosine similaritily between two vectors:",cos_sim(vec1,vec2))

cosine similaritily between two vectors: 0.9746318461970762
